module.exports = {
  CardBean: require('./CardBean.png'),
  CardBolt: require('./CardBolt.png'),
  CardClassic: require('./CardClassic.png'),
  CardGanster: require('./CardGangster.png'),
  CardMozart: require('./CardMozart.png'),
  CardNot: require('./CardNot.png'),
  CardSmall: require('./CardSmall.png'),
  CardSwag: require('./CardSwag.png'),
  CardWolf: require('./CardWolf.png'),
  CardWork: require('./CardWork.png'),
  CardBear: require('./CardBear.png'),
  CardMyspace: require('./CardMyspace.png'),
  CardEvil: require('./CardEvil.png'),
  Zero: require('./zero.png'),
  One: require('./one.png'),
  Two: require('./two.png'),
  Three: require('./three.png'),
  Four: require('./four.png'),
};
